### ISSUE TITLE
Summary does not introduce AMR

### ISSUE THREAD

**Issue by jwallwork23** [DLR-AMR/t8code_JOSS#10]
The "Summary" section does not say what mesh adaptation / AMR actually does, i.e., vary resolution to reduce approximation errors "where they matter" and reduce computational costs elsewhere. This is mentioned in the "Statement of Need" section but - given the summary is meant to be for a non-specialist audience - it would be good to have a sentence explaining this. Perhaps the introductory sentence could just be moved from the "Statement of Need" section to the "Summary".

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
I added a sentence to the summary section.

**Comment by jwallwork23** [comment]
Thanks for this. I'm happy for this issue to be closed.
