### ISSUE TITLE
How does t8code compare to other software?

### ISSUE THREAD

**Issue by jwallwork23** [DLR-AMR/t8code_JOSS#11]
In the "Statement of Need" section, please elaborate on who the target audience of `t8code` is, as well as the relation of `t8code` to other work. Please also discuss how this software compares to other available AMR tools.

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
I elaborated on the target audience and listed the most widely used AMR packages. I also highlighted what t8code distinguishes it from the other libraries.

**Comment by jwallwork23** [comment]
You missed a full stop "." after "pyramids" on L41. Other than that, it reads well, thanks.

**Comment by jmark** [comment]
Thank you catching the typo! Fixed. I'll close the issue then. Feel free to re-open it in case there is still something missing.
