### ISSUE TITLE
Additional info in Statement of Need 

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#12]
In the section "Statement of Need", after having briefly described t8code’s efficiency strategy (lines 23-30), I believe it would be also useful to highlight how one can interface t8code. A series of applications has already been provided in the Summary, but in specific, is t8code limited to finite element packages? What is its relation with the mesher? What would I need to insert it in a novel software pipeline?

(Part of JOSS review: https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
I elaborated a bit more on the usage with t8code. Moreover, I reference to our overview paper which gives more details on how t8code is used.
