### ISSUE TITLE
Missing statement of the field

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#13]
Neither "Statement of Need" nor "Fundamental Concept" seem to report a statement of the field, required by JOSS review checklist. I see value in a comparison with other commonly used packages so to place t8code in the spectrum of available options. Examples: what are the pros and cons of existing packages and how do they relate to t8code? Has the management structure of t8code been applied to other fields? If yes which ones were of inspiration?

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
I added a list of common AMR packages and what t8code distinguishes it from them.

**Comment by jmark** [comment]
> Has the management structure of t8code been applied to other fields? If yes which ones were of inspiration?

Can you elaborate on what you exactly mean by this question?

**Comment by alecontri** [comment]
I meant if the same concepts had been applied in other contexts, but I see now that in lines 78-79 you reference prior works on the same subject and I guess that solves the problem. Thanks
