### ISSUE TITLE
Scalability statement comparison

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#14]
Related to #11, a statement on the scalability of the software is done, but no comparison with other packages is actually presented. I think the audience expects an overview of how t8code scales with respect to other softwares on the market. Please add a table/graph for comparison.

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
You have a valid point there. I have to check if we have such kind of data.

**Comment by jmark** [comment]
I will add this result to the JOSS paper in the next days.

**Comment by jmark** [comment]
I added above plot with a bit of discussion into the text: https://github.com/DLR-AMR/t8code_JOSS/blob/main/paper.pdf

**Comment by jmark** [comment]
This issue is considered resolved according to: https://github.com/openjournals/joss-reviews/issues/6887#issuecomment-2483702086
