### ISSUE TITLE
Doubt on `t8code` coupled with numerical methods

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#15]
In Line 39 you affirm that ‘the trees are refined recursively in a structured pattern’. This means that there will be interfaces with different number of elements on the different sides. Does this limit the applicability of the package to specific numerical methods that are able to handle this, such as the considered Discontinuous Galerkin method?

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
Yes, indeed. This refinement pattern leads to non-conforming interfaces between finer and coarser refinement levels. Finite Volume and Disc. Galerkin methods can easily handle this via, for example, mortar methods. However, we are working on hanging nodes resolving routines for t8code which transforms the mesh back to a conforming one after adaptation has been applied.

**Comment by jmark** [comment]
I add a sentence explaining this in the related section.

**Comment by alecontri** [comment]
Perfect, thanks!
