### ISSUE TITLE
Comments on papers' figures

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#16]
Some comments on the figures:

- Figure 1: To my understanding it shows an example of a mesh refined using t8code, but no other information is provided. I think it would bring much more clarity to exemplify the steps that lead to such figure. What is the starting structured/unstructured mesh? What is the difference in ending refinement between previous strategies and this one using the same refinement criteria? Using subfigures to graphically show the differences;
- Figure 2: I believe the figure was created to graphically exemplify t8code’s strategy, but I find it unclear. I do not separate an upper and a bottom part, so the bottom-left indication is cumbersome. Also, I would keep it simple and show the logic of just a single refinement step, which is the strength of the proposed approach, so to keep the figure digestible at a glance. 
- Figure 3: I am aware of the complexity of the code and the challenges associated with benchmarking complex softwares, however this plot is difficult to interpret. Not only is the y-axis presented in log scale, but also the use of many colors makes it difficult to interpret the specific contributions of t8code. If the main goal is to illustrate the 15% total time contribution of t8code, better graphical representations of this which are easier to interpret for the reader could be helpful.

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
I reworked/exchanged the figures and made them more comprehensible. Thank you for your suggestions.
