### ISSUE TITLE
Small comments on paper's links

### ISSUE THREAD

**Issue by alecontri** [DLR-AMR/t8code_JOSS#17]
- The link to [www.dlr-amr.github.io/t8code](http://www.dlr-amr.github.io/t8code) in the Summary leads to a 404 error page;
- The link to PADME-AM project leads to a conference abstract. Not necessary, but maybe it is better to link to the project page?

(Part of JOSS review https://github.com/openjournals/joss-reviews/issues/6887.)

**Comment by jmark** [comment]
Fixed.
